[package]
edition = "2021"
name = "ksv"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "3.1.5", features = ["derive"]}
csv = "1.1.6"
rand = "0.8.5"
tabled = "0.5.0"
